src/WebMVC/Models/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace WebMVC.Models
{
    public class CityViewModel
    {
        [Required]
        public string CityName { get; set; }

        public string Country { get; set; }

        public List<CityDetails> Results { get; set; }

        public bool HasResults => Results != null && Results.Any();

        public List<RequestViewModel> LatestQueries { get; set; }

        public bool HasQueries => LatestQueries != null && LatestQueries.Any();
    }

    public class CityDetails
    {
        public string Location { get; set; }
        public string City { get; set; }
        public string Country { get; set; }

        public string CityAndCountry
        {
            get
            {
                return $"{City} ({Country})";
            }
        }

        public List<Measurement> Measurements { get; set; }

        public string MaxValue { get; set; }
        public string MinValue { get; set; }
        public int RangeOfDays { get; set; }
        public bool HasMeasurements => Measurements != null && Measurements.Any();
    }

    public class Measurement
    {
        public string Parameter { get; set; }
        public double Value { get; set; }
        public DateTime LastUpdated { get; set; }
        public string Unit { get; set; }
        public string SourceName { get; set; }
    }

    public class RequestViewModel
    {
        public string City { get; set; }

        public string Country { get; set; }

        public string CityFullName
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Country))
                    return City;
                return $"{City} [{Country}]";
            }
        }
    }
}

src/WebMVC/Models/ErrorViewModel.cs
using System;

namespace WebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebMVC/Controllers/AirQualityController.cs
using Core.DomainServices;
using Core.Enums;
using Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebMVC.Models;
using WebMVC.Services;
using CORE = Core.Models;

namespace WebMVC.Controllers
{
    public class AirQualityController : Controller
    {
        private readonly IOpenAirQualityService _aqService;
        private readonly ICityDetailsRequestService _cityDetailsRequestService;

        public AirQualityController(IOpenAirQualityService aqService, ICityDetailsRequestService cityDetailsRequestService)
        {
            _aqService = aqService;
            _cityDetailsRequestService = cityDetailsRequestService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(CityViewModel model)
        {
            if (ModelState.IsValid)
            {
                var request = new CORE.GetCityDetailsRequest
                {
                    Limit = 100,
                    City = model.CityName,
                    Country = model.Country,
                    Page = 1,
                    Sort = Sorting.Asc
                };
                var latestQueries = _cityDetailsRequestService.AddAndGetLatest(request);
                model.LatestQueries = Mapper.Map(latestQueries);

                var measurements = await _aqService.GetLatestMeasurements(request);
                model.Results = Mapper.Map(measurements.Results);
            }

            return View("Index", model);
        }
    }
}

src/WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult AirQuality()
        {
            ViewData["Message"] = "Your city's Air Quality here.";

            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebMVC/Views/AirQuality/Index.cshtml
@model WebMVC.Models.CityViewModel
@{
    ViewData["Title"] = "Air Quality";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>This area to provide information about quality AIR.</p>

@using (Html.BeginForm("Details", "AirQuality", FormMethod.Post))
{
    @Html.TextBoxFor(model => model.CityName)
    @Html.ValidationMessageFor(model => model.CityName)

    @Html.TextBoxFor(model => model.Country)
    @Html.ValidationMessageFor(model => model.Country)
    <button type="submit">Get Latest</button>
}
<br />

@if (Model != null && Model.HasQueries)
{
    <div class="list-group-status">
        <h3>
            LATEST QUERIES
        </h3>
        @foreach (var query in Model.LatestQueries)
        {
            <div class="row list-group-status-item">
                <div class="col-md-9">
                    @Html.ActionLink(query.CityFullName, "Details", "AirQuality", new { CityName = query.City, Country = query.Country }, null)
                </div>
            </div>
        }
    </div>

}
else
{
    <div>
        <h3>
            THERE ARE NO QUERIES
        </h3>
    </div>
}

@if (Model != null && Model.HasResults)
{
    <div class="row">

        @foreach (var cityDetails in Model.Results)
        {
            <div class="">
                @Html.Partial("_cityMeasurements", cityDetails)
            </div>
            <br />
        }
    </div>
}
else
{

    <div>
        <h3>
            THERE ARE NO MEASUREMENTS
        </h3>
    </div>
}

src/WebMVC/Views/AirQuality/_cityMeasurements.cshtml
@model CityDetails

<div>
    <div class="container col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                @Model.CityAndCountry
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    @Html.Partial("_details", @Model)
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                                <tr>
                                    <th>Parameter</th>
                                    <th>Value</th>
                                    <th>Unit</th>
                                    <th>LastUpdated</th>
                                    <th>SourceName</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var measurement in @Model.Measurements)
                                {
                                    @Html.Partial("_measurement", measurement)
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

src/WebMVC/Views/AirQuality/_details.cshtml
@model CityDetails
<div>
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12 text-left">
                            <div>Location: </div>
                            <div>@Model.Location</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12 text-center">
                            <div>Number of days</div>
                            <div>@Model.RangeOfDays</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <div>MIN value</div>
                            <div>@Model.MinValue</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">

                        <div class="col-xs-12 text-right">
                            <div>MAX value</div>
                            <div>@Model.MaxValue</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/WebMVC/Views/AirQuality/_measurement.cshtml
@model Measurement

<div>
    <div>
        <div class="row">
            <tr>
                <td>@Model.Parameter</td>
                <td>@Model.Value</td>
                <td>@Model.Unit</td>
                <td>@Model.LastUpdated</td>
                <td>@Model.SourceName</td>
            </tr>
        </div>
    </div>
</div>

src/WebMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/WebMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="AirQuality" asp-action="Index">Air Quality</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>